version: "3.7"

services:
  db:
    container_name: db
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data/:/var/lib/postgresql/data/
    environment:
        # POSTGRES_PASSWORD: password
        # POSTGRES_DB: vocabulary
    networks:
      - db
    restart: always

networks:
  db:
